### ISSUE TITLE
New desing NGO registration

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/ajut.md#11]
- must contain:
- [ ] new sidebar, only with text, delete all the other blocks from sidebar
- [ ] Registration form

[figma url](https://www.figma.com/proto/Fm1mdnskOPnJCX1AWgpR3U/Ajut.md_Web-Design_UI?scaling=min-zoom&node-id=106%3A1330)

![image](https://user-images.githubusercontent.com/10476109/92494296-374cf900-f1fe-11ea-97e1-8697a8281ac9.png)

**Comment by vitaliel** [comment]
I will take it.
