### ISSUE TITLE
[Currency] - Remove RON and add MDL into supported currency list

### ISSUE THREAD

**Issue by alexkingdom** [code4moldova/ajut.md#20]
![image](https://user-images.githubusercontent.com/57179803/92622103-58304f80-f2cd-11ea-95d5-156934516533.png)
![image](https://user-images.githubusercontent.com/57179803/92627053-86b12900-f2d3-11ea-9509-8d1dbb85ae59.png)

We support only MDL, USD, EUR so we need to remove RON from all the places.

**Comment by grig-ian-theo** [comment]
hey, hai eu fac asta

**Comment by alexkingdom** [comment]
> 
> 
> hey, hai eu fac asta

Maine fac review si vad daca nu ai uitat nimic :) Ms.
