### ISSUE TITLE
Improve donation form (big task) (mostly backend)

### ISSUE THREAD

**Issue by alexkingdom** [code4moldova/ajut.md#26]
We have donation form like in screenshot below:
![image](https://user-images.githubusercontent.com/57179803/92992926-023ef000-f4f7-11ea-9793-44ecddd1dd6d.png)
As you can see, user can fill the amount of how much money want to transfer and will be processed by some processing system (Netopia).
In our case, we not will use any processing system like this. So we decided to make following things:

Organization part:

Should be able to set up payment methods on which they will receive money (paypal & bank transfer).
For paypal we will ask just email.
For bank transfer need to define the filds (Address, bank name, Iban and maybe something like BIC)

User part:

1. When user select to donate money, he just will select some available payment method
2. Will be form like in screenshot above (even on bank transfer), and will be asked to fill amount
3. After this user will see details of selected payment method (for paypal for start we can just show email, for bank, all details)

Form that was submitted by user will be saved into db (maybe we already something have, just need to integrate new behavior). So all donation will be reported to organization and they must confirm the payment and amount that was confirmed just because we need to know how much money was donated.

Maybe full flow of this will be made later.
This task should be discussed more. Need to check what we have already and what need to do.

**Comment by johnsmithm** [comment]
after discussions with UX team, I understand we do not need to create a functionality for changing the amount in ngo admin page, just an action to approve the payment(the money are arrived in the bank).
