### ISSUE TITLE
New design for the header

### ISSUE THREAD

**Issue by johnsmithm** [code4moldova/ajut.md#4]
must contain:
- [ ] align the title and the text to the left of the section
- [ ] add an image to the right of the section
- [ ] add background color and round corners
- [ ] add different  icons for each filter button
- [ ] add the background color and round corners for the filter buttons
- [ ] when a filter button is clicked change the background color of the section above and the background color of the button

[figma link](https://www.figma.com/proto/Fm1mdnskOPnJCX1AWgpR3U/Ajut.md_Web-Design_UI?scaling=min-zoom&node-id=1%3A2)

![image](https://user-images.githubusercontent.com/10476109/92329061-ab0bcc00-f06d-11ea-9919-65c85cc198ad.png)

**Comment by vitaliel** [comment]
I will take it.
